# name to be displayed in the github ui
name: Rust Builds

# triggers 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# env variables to run cmds with
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

# all the jobs to run 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust 
      uses: actions-rs/toolchain@v1
      with: 
        toolchain: stable
        override: true
    - name: Check formatting 
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests 
      run: cargo test --verbose
    