# name to be displayed in the github ui
name: Rust Builds

# triggers 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# env variables to run cmds with
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

# all the jobs to run 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # checks out your repository code so the workflow can access it
    - name: Install Rust 
      uses: actions-rs/toolchain@v1 # installs the Rust toolchain, making sure stable Rust is available
      with: 
        toolchain: stable
        override: true
    - name: Change directory
      run: cd enigma-core
    - name: Check formatting 
      run: cargo fmt -- --check # checks if code is formatted properly without changing files
    - name: Build
      run: cargo build --verbose # compiles the Rust project with detailed output
    - name: Run tests 
      run: cargo test --verbose # runs the test suite with detailed output
